#!perl

use strict;
use warnings;
use Getopt::Std;
use Plugtools;

$Getopt::Std::STANDARD_HELP_VERSION = 1;

#version function
sub main::VERSION_MESSAGE {
	print "plgrm 0.0.0\n";
}

#print help
sub main::HELP_MESSAGE {
	print "\n"
		. "-g <group name>  - The group to remove.\n" . "\n"
		. "For more info, see the the perldocs for Plugtools and plgrm...\n"
		. "perldoc plgrm\n"
		. "perldoc Plugtools\n";
}

#gets the options
my %opts = ();
getopts( 'g:', \%opts );

if ( !defined( $opts{g} ) ) {
	warn('plgrm:254: No group name specified');
	exit 254;
}

my $pt = Plugtools->new;
if ( $pt->{error} ) {
	warn('plgrm: Failed to initialize the Plugtools object');
	exit $pt->{error};
}

$pt->deleteGroup( $opts{g} );
if ( $pt->{error} ) {
	warn('plgrm: Failed to remove the group');
	exit $pt->{error};
}

exit 0;

=head1 NAME

plgrm - Remove a group from LDAP.

=head1 SYNOPSIS

plgrm B<-g> <group>

=head1 SWITCHES

=head2 -g <group>

This specifies the group to remove.

=head1 EXIT CODES

If the exit code is not listed below, it is what was the error code returned by Plugtools.

=head2 254

No group specified.

=head1 ACKNOWLEDGEMENTS

=head1 LICENSE AND COPYRIGHT

This software is Copyright (c) 2023 by Zane C. Bowers-Hadley.

This is free software, licensed under:

  The Artistic License 2.0 (GPL Compatible)

=cut
