#!perl

use strict;
use warnings;
use Getopt::Std;
use Plugtools;

$Getopt::Std::STANDARD_HELP_VERSION = 1;

#version function
sub main::VERSION_MESSAGE {
	print "pluadd 0.0.1\n";
}

#print help
sub main::HELP_MESSAGE {
	print "\n"
		. "-u <user name>  - The user to add.\n"
		. "-U <UID>  - The UID for the new user.\n"
		. "-g <group name>  - The primary group name for the user.\n"
		. "-G <GID>  - The GID to use for when adding the primary group.\n"
		. "-c <gecos>  - The GECOS value for new user.\n"
		. "-h <home>  - The home directory for the new user.\n"
		. "-s <shell>  - The shell for the new user.\n"
		. "-H <createHome>  - A boolean value describing if the home directory should be created.\n"
		. "-S <skel>  - The skeleton to use for the directory to use.\n"
		. "-p <chmodHome>  - A boolean value describing if the home directory should be chmoded or not.\n"
		. "-P <chmodValue>  - The chmod value for home.\n"
		. "-O <chownHome>  - A boolean value describing if the home directory should be chowned or not.\n"
		. "-l  - Call \$entry->dump on any new objects.\n" . "\n"
		. "createHome:\n"
		. "The this overrides the default value. If nothing is specified, the default value is '1'.\n" . "\n"
		. "skel:\n"
		. "This overrides the default value. If nothing is specified, '/etc/skel' is used.\n" . "\n"
		. "chownHome:\n"
		. "This overrides the default value. If nothing is specified, '1' is used.\n" . "\n"
		. "chownValue:\n"
		. "This overrides te default value. If nothing is specified, '640' is used.\n" . "\n"
		. "For more info, see the the perldocs for Plugtools and pluadd...\n"
		. "perldoc pluadd\n"
		. "perldoc Plugtools\n";
} ## end sub main::HELP_MESSAGE

#gets the options
my %opts = ();
getopts( 'u:U:g:G:c:h:s:H:S:p:P:O:l', \%opts );

if ( !defined( $opts{u} ) ) {
	warn('pluadd:254: No user specified.');
	exit 254;
}

my $pt = Plugtools->new;
if ( $pt->{error} ) {
	warn('pluadd: Failed to initialize the Plugtools object');
	exit $pt->{error};
}

$pt->addUser(
	{
		user       => $opts{u},
		uid        => $opts{U},
		group      => $opts{g},
		gid        => $opts{G},
		gecos      => $opts{c},
		shell      => $opts{s},
		home       => $opts{h},
		createHome => $opts{H},
		chownHome  => $opts{O},
		chmodHome  => $opts{p},
		chmodValue => $opts{P}
	}
);
if ( $pt->{error} ) {
	warn('pluadd: Failed to add the user');
	exit $pt->{error};
}

exit 0;

=head1 NAME

pluadd - Add a user to LDAP.

=head1 SYNOPSIS

plurm B<-u> <user> [B<-U> <UID>] [B<-g> <group>] [B<-G> <GID>] [B<-c> <GECOS>] [B<-h> <home>] [B<-s> <shell>] [B<-S> <skel>] [B<-H> (0|1)] [B<-O> (0|1)] [B<-p> (0|1)] [B<-P> <chmodValue>] [B<-l>]

=head1 SWITCHES

=head2 -u <user>

This specifies the user to add.

=head2 -U <UID>

The UID for the new user.

=head2 -g <group>

The group primary group for the user.

=head2 -G <GID>

The GID for the primary group.

=head2 -c <GECOS>

The GECOS field for the new user.

=head2 -h <home>

The home directory for the new user.

=head2 -s <shell>

The shell for the new user.

=head2 -S <skel>

The skeleton directory to use if the user directory is to be created.

=head2 -H (0|1)

Override the default of config specified setting creating the home directory.

=head2 -O (0|1)

Override the default of config specified setting chowning the home directory.

=head2 -p (0|1)

Override the default of config specified setting chmoding the home directory.

=head2 -P <chownValue>

Override the default of config specified setting number to use for chmoding the home directory.

=head2 -l

Print any newly created or modified entries.

=head1 EXIT CODES

If the exit code is not listed below, it is what was the error code returned by Plugtools.

=head 254

No user specified.

=head1 ACKNOWLEDGEMENTS

=head1 LICENSE AND COPYRIGHT

This software is Copyright (c) 2023 by Zane C. Bowers-Hadley.

This is free software, licensed under:

  The Artistic License 2.0 (GPL Compatible)

=cut
