#!perl

use strict;
use warnings;
use Getopt::Std;
use Plugtools;

$Getopt::Std::STANDARD_HELP_VERSION = 1;

#version function
sub main::VERSION_MESSAGE {
	print "plurm 0.0.0\n";
}

#print help
sub main::HELP_MESSAGE {
	print "\n"
		. "-u <user>  - The user to remove.\n"
		. "-H <removeHome>  - A boolean value that specifies if the home directory for the user should be removed.\n"
		. "-G <removeGroup>  - A boolean value that specifies if the primary group should be removed if empty.\n" . "\n"
		. "removeHome:\n"
		. "The default value for this is false, '0'.\n" . "\n"
		. "removeGroup:\n"
		. "The default value for this is truem, '1'.\n" . "\n"
		. "For more info, see the the perldocs for Plugtools and plurm...\n"
		. "perldoc plurm\n"
		. "perldoc Plugtools\n";
} ## end sub main::HELP_MESSAGE

#gets the options
my %opts = ();
getopts( 'u:G:H:', \%opts );

if ( !defined( $opts{u} ) ) {
	warn('plgrm:254: No user name specified');
	exit 254;
}

my $pt = Plugtools->new;
if ( $pt->{error} ) {
	warn('plgrm: Failed to initialize the Plugtools object');
	exit $pt->{error};
}

$pt->deleteUser(
	{
		user        => $opts{u},
		removeHome  => $opts{H},
		removeGroup => $opts{G},
	}
);
if ( $pt->{error} ) {
	warn('plgrm: Failed to remove the group');
	exit $pt->{error};
}

exit 0;

=head1 NAME

plurm - Remove a user from LDAP.

=head1 SYNOPSIS

plurm B<-u> <user> [B<-H> (0|1)] [B<-G> (0|1)]

=head1 SWITCHES

=head2 -u <user>

This specifies the user to remove.

=head2 -H (0|1)

This allows the default or config specified value for if the home
directory should be remove or not.

=head2 -G (0|1)

This allows the default or config specified value for if the primary
group should be remove or not if it is empty.

=head1 EXIT CODES

If the exit code is not listed below, it is what was the error code returned by Plugtools.

=head2 254

No user specified.

=head1 ACKNOWLEDGEMENTS

=head1 LICENSE AND COPYRIGHT

This software is Copyright (c) 2023 by Zane C. Bowers-Hadley.

This is free software, licensed under:

  The Artistic License 2.0 (GPL Compatible)

=cut
